version: '3.7'

networks:
  private:


services:
  pghost:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$user
      - POSTGRES_PASSWORD=$password
      - POSTGRES_DB=$db
    networks:
      - private
  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - pghost
    networks:
      - private
    ports:
      - "$port:$port"
    command: "/app/run.sh"

